FROM centos:centos7

RUN yum update
RUN yum install -y sudo vim git curl
RUN yum install -y epel-release
RUN yum install -y nodejs npm

RUN npm install -g n
RUN npm install -g @angular/cli

CMD [ "node" ]

